EPSILON_DECAY_RATE = 0.99
MIN_EPSILON = 0.05
GAMMA = 0.90
BATCH_SIZE = 64
LEARNING_RATE = 0.00025
MEMORY_SIZE = 30000
COPY_STEPS = 500

CHECKPOINT_AMOUNT = 500
EPISODES = 5000
EPSILON = 0.05
REPLAY_FRAME_COUNT = 4
SKIP_AND_STACK_AMOUNT = 4
ENV_HEIGHT = 84
ENV_WIDTH = 84

WOLRD = "SuperMarioBros-1-1-v0"


MODEL_SAVE_DIR = "models"

MODEL_SAVE_NAME = f"{MODEL_SAVE_DIR}/DDQN-MARIO-v1.pt"
TARGET_MODEL_SAVE_NAME = f"{MODEL_SAVE_DIR}/Target-DDQN-MARIO-v1.pt"

REPLAY_BUFFER_DIR = "memory"

STATE_SAVE_NAME = f"{REPLAY_BUFFER_DIR}/state_mem.pt"
ACTION_SAVE_NAME = f"{REPLAY_BUFFER_DIR}/action_mem.pt"
REWARD_SAVE_NAME = f"{REPLAY_BUFFER_DIR}/reward_mem.pt"
NEXT_STATE_SAVE_NAME = f"{REPLAY_BUFFER_DIR}/next_state_mem.pt"
DONE_SAVE_NAME = f"{REPLAY_BUFFER_DIR}/done_mem.pt"


PICKLE_FOLDER_NAME = "pickle"
TOTAL_REWARDS_PICKLE = f"{PICKLE_FOLDER_NAME}/total_rewards.pkl"
NUM_IN_QUEUE_PICKLE = f"{PICKLE_FOLDER_NAME}/num_in_queue.pkl"
ENDING_POSISTION_PICKLE = f"{PICKLE_FOLDER_NAME}/ending_position.pkl"