EPSILON_DECAY_RATE = 0.999999
MIN_EPSILON = 0.01
GAMMA = 0.99
BATCH_SIZE = 32
LEARNING_RATE = 0.0001
MEMORY_SIZE = 200000
COPY_STEPS = 500

EPISODES = 3000
EPSILON = 1
REPLAY_FRAME_COUNT = 4
SKIP_AND_STACK_AMOUNT = 4
ENV_HEIGHT = 84
ENV_WIDTH = 84

WOLRD = "SuperMarioBros-1-1-v0"


MODEL_SAVE_DIR = "models"

MODEL_SAVE_NAME = f"{MODEL_SAVE_DIR}/DDQN-MARIO-v1.pt"
TARGET_MODEL_SAVE_NAME = f"{MODEL_SAVE_DIR}/Target-DDQN-MARIO-v1.pt"

REPLAY_BUFFER_DIR = "memory"

STATE_SAVE_NAME = f"{REPLAY_BUFFER_DIR}/sate_mem.pt"
ACTION_SAVE_NAME = f"{REPLAY_BUFFER_DIR}/action_mem.pt"
REWARD_SAVE_NAME = f"{REPLAY_BUFFER_DIR}/reward_mem.pt"
NEXT_STATE_SAVE_NAME = f"{REPLAY_BUFFER_DIR}/next_state_mem.pt"
DONE_SAVE_NAME = f"{REPLAY_BUFFER_DIR}/done_mem.pt"
